# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='calls/%Y/%m/%d/', verbose_name='Аудио файл')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('web', 'Веб интерфейс'), ('telegram', 'Telegram'), ('api', 'API')], default='web', max_length=20, verbose_name='Источник')),
                ('language', models.CharField(default='ru', max_length=5, verbose_name='Язык')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', '-created_at'], name='calls_call_user_id_created_idx'),
                    models.Index(fields=['status'], name='calls_call_status_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст транскрипции')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Уверенность (%)')),
                ('segments', models.JSONField(default=list, verbose_name='Сегменты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='calls.call', verbose_name='Звонок')),
            ],
            options={
                'verbose_name': 'Транскрипция',
                'verbose_name_plural': 'Транскрипции',
            },
        ),
        migrations.CreateModel(
            name='CallNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='calls.call', verbose_name='Звонок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('complaint', 'Жалоба'), ('order', 'Заказ'), ('support', 'Поддержка'), ('inquiry', 'Запрос'), ('other', 'Другое')], max_length=20, null=True, verbose_name='Категория')),
                ('keywords', models.JSONField(default=list, verbose_name='Ключевые слова')),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тональность')),
                ('word_frequency', models.JSONField(default=dict, verbose_name='Частота слов')),
                ('speaker_stats', models.JSONField(default=dict, verbose_name='Статистика говорящих')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Краткое содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='calls.call', verbose_name='Звонок')),
            ],
            options={
                'verbose_name': 'Анализ звонка',
                'verbose_name_plural': 'Анализы звонков',
            },
        ),
    ]
