# Generated by Django 5.0.1 on 2025-12-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='call',
            new_name='calls_call_user_id_ed5279_idx',
            old_name='calls_call_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='call',
            new_name='calls_call_status_03473e_idx',
            old_name='calls_call_status_idx',
        ),
    ]
