# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('total_calls', models.IntegerField(default=0, verbose_name='Всего звонков')),
                ('completed_calls', models.IntegerField(default=0, verbose_name='Завершенных звонков')),
                ('failed_calls', models.IntegerField(default=0, verbose_name='Ошибок обработки')),
                ('total_duration', models.FloatField(default=0, verbose_name='Общая длительность (сек)')),
                ('average_duration', models.FloatField(default=0, verbose_name='Средняя длительность (сек)')),
                ('categories_stats', models.JSONField(default=dict, verbose_name='Статистика по категориям')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Ежедневный отчет',
                'verbose_name_plural': 'Ежедневные отчеты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calls', models.IntegerField(default=0, verbose_name='Всего звонков')),
                ('total_duration', models.FloatField(default=0, verbose_name='Общая длительность (сек)')),
                ('last_call_date', models.DateTimeField(blank=True, null=True, verbose_name='Последний звонок')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика пользователя',
                'verbose_name_plural': 'Статистика пользователей',
            },
        ),
    ]
